epochs:
  desc: Number of epochs to train over
  value: 100

batch_size:
  desc: Mini-batch size
  value: 64

learning_rate:
  desc: Step size for optimizer
  value: .001

val_ratio:
  desc: Validation - training set split ratio
  value: .2

dataset:
  desc: Dataset to run experiments on
  value: CIFAR10

model:
  desc: Model to train with
  value: Ampere_Resnet18
