name: Resnet18_CIFAR100
project: ampere_acc_test
entity: tejalapeno
program: train/train.py

method: grid

parameters:
  model:
    value: Resnet18
  epochs:
    value: 100
  dataset:
    value: CIFAR100
  batch_size:
    values: [64, 128, 256]
  learning_rate:
    value: .001
  val_ratio:
    value: .2
<<<<<<< HEAD
=======

early_terminate:
  type: hyperband
  s: 2
  eta: 3
  max_iter: 27
>>>>>>> 3f6396d83b286ba2add4f3b12e9835af50e22ad9
